// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const provider = normalizeProvider(process.env["DATABASE_PROVIDER"]);

export default defineConfig({
  schema: `prisma/schema.${provider}.prisma`,
  migrations: {
    path: `prisma/migrations/${provider}`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

function normalizeProvider(provider?: string) {
  switch (provider) {
    case undefined:
    case "":
    case "sqlite":
      return "sqlite";
    case "postgres":
    case "postgresql":
      return "postgresql";
    case "mysql":
    case "mariadb":
      return "mysql";
    default:
      throw new Error(
        `Unsupported DATABASE_PROVIDER "${provider}". Use sqlite, postgresql, or mysql.`,
      );
  }
}
